apiVersion: v1
kind: Service
metadata:
  name: {{ include "kashti.fullname" . }}
  labels:
    {{- include "kashti.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
  {{- if .Values.tls.enabled }}
  - name: https
    port: 443
    targetPort: 443
    nodePort: {{ .Values.service.tlsNodePort }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "kashti.selectorLabels" . | nindent 8 }}
    {{- include "kashti.labels" . | nindent 8 }}
